---
title: "Part II - Logistic Regression"
author: "Sanjeev Gadre"
date: "November 04, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = TRUE)
```

Loading the required libraries

```{r libraries, message=FALSE}
library(dplyr)
library(ggplot2)
library(ff)
library(ffbase)
library(biglm)

# Creating ffdir where ff objects can be stored and retrieved
ffdir = paste(getwd(), "/ffdir", sep = "")
if (!dir.exists(ffdir)){dir.create(ffdir)}

```

### Getting data

```{r get-data}
train = load.ffdf(dir = "../RDA/traindir")
train = train[["train"]]
open.ffdf(train)

```

### Building the Logistic Regression Model

```{r logit-model}
p = ncol(train) - 1
f = paste("target", "~", colnames(train)[1], sep = "")
for (k in 2:p) {
  f = paste(f, "+", colnames(train)[k], sep = "")
}

f = as.formula(f)
logit.model = bigglm.ffdf(f, data = train, family = binomial())

prob = ff(as.numeric(NA), length = nrow(train))
pred = ff(as.numeric(NA), length = nrow(train))
chunks = chunk.ffdf(train)

for (chunkrangeindex in chunks) {
  prob[chunkrangeindex] = predict(logit.model, newdata = train[chunkrangeindex, ], type = "response")
  
}

pred = ifelse(prob[] < 0.5, 0, 1)
  
mean(train[, "target"] == pred[])

```
